#!/bin/bash

### BEGIN INIT INFO
# Provides:        SERVICE_NAME_PLACEHOLDER
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Start autossh
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
. /lib/lsb/init-functions

DAEMON=/usr/bin/autossh
PIDFILE=/var/run/autosshd.pid
AUTOSSH_OPTS="-M 0 -f -nNT -F CONFIG_LOCATION_PLACEHOLDER tunnel"
LOCKFILE=/var/lock/autosshd

export AUTOSSH_PIDFILE="$PIDFILE"

test -x $DAEMON || exit 5

lock_tunnel() {
  if [ -x /usr/bin/lockfile-create ]; then
    lockfile-create $LOCKFILE
    lockfile-touch $LOCKFILE &
    LOCKTOUCHPID="$!"
  fi
}

unlock_tunnel() {
  if [ -x /usr/bin/lockfile-create ] ; then
    kill $LOCKTOUCHPID
    lockfile-remove $LOCKFILE
  fi
}

case $1 in
  start)
    log_daemon_msg "Starting autossh" "autosshd"
    lock_tunnel
      start-stop-daemon --start --pidfile $PIDFILE --startas $DAEMON -- $AUTOSSH_OPTS
      status=$?
    unlock_tunnel
    log_end_msg $status
      ;;
  stop)
    log_daemon_msg "Stopping autossh" "autosshd"
      start-stop-daemon --stop --retry=TERM/30/KILL/5 --pidfile $PIDFILE
    log_end_msg $?
    rm -f $PIDFILE
      ;;
  restart|force-reload)
    $0 stop && sleep 2 && $0 start
      ;;
  try-restart)
    if $0 status >/dev/null; then
      $0 restart
    else
      exit 0
    fi
    ;;
  reload)
    exit 3
    ;;
  status)
    status_of_proc $DAEMON "autosshd"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
    exit 2
    ;;
esac
